version: "3.8"
networks:
  webapp_B:
    driver: macvlan
    driver_opts:
      parent: ens19.3
    name: webapp_B
    ipam:
      config:
        - subnet: "10.0.3.0/24"
          gateway: "10.0.3.254"
  internal_B:
    driver: macvlan
    driver_opts:
      parent: ens19.2
    name: internal_B
    ipam:
      config:
        - subnet: "10.0.2.0/24"
          gateway: "10.0.2.254"
  dmz_B:
    driver: macvlan
    driver_opts:
      parent: ens19.1
    name: dmz_B
    ipam:
      config:
        - subnet: "10.0.1.0/24"
          gateway: "10.0.1.254"
  pubnet_B:
    name: pubnet_B
    ipam:
      config:
        - subnet: "172.31.255.0/24"
          gateway: "172.31.255.254"

services:
  # PUBLIC NET
  er_b:
    build: ./edge_router
    container_name: er_b
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    networks:
      dmz_B:
        ipv4_address: er_b_dmz_b
      pubnet_B:
        ipv4_address: er_b_pubnet_b
    command: ["172.31.255.254", "10.0.1.0/24", "10.0.0.0/8", "10.0.1.2"]
  external_host_b:
    build: ./router
    container_name: external_host_b
    cap_add:
      - NET_ADMIN
    networks:
      pubnet_B:
        ipv4_address: 172.31.255.100
    command: ["172.31.255.253"]

  # DMZ
  ## ROUTERS
  r_b:
    build: ./router
    container_name: r_b
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    networks:
      internal_B:
        ipv4_address: 10.0.2.1
      dmz_B:
        ipv4_address: 10.0.1.2
    command: ["10.0.1.1"]
  ## WEBAPP (deals with webapp net)
  webapp_worker1:
    build: ./webapp_worker
    container_name: webapp_worker1
    networks:
      webapp_B:
        ipv4_address: 10.0.3.2
  webapp_worker2:
    build: ./webapp_worker
    container_name: webapp_worker2
    networks:
      webapp_B:
        ipv4_address: 10.0.3.3
  webapp:
    build: ./webapp
    container_name: webapp
    cap_add:
      - NET_ADMIN
    networks:
      webapp_B:
        ipv4_address: 10.0.3.1
      dmz_B:
        ipv4_address: 10.0.1.5
    command: ["10.0.1.2"]

  # INTERNAL
  dhcp_b:
    build: ./dhcp
    container_name: dhcp_b
    networks:
      internal_B:
        ipv4_address: 10.0.2.4
    command: ["10.0.2."]
  ## DB
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      internal_B:
        ipv4_address: 10.0.2.2
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      internal_B:
        ipv4_address: 10.0.2.3
  ## EMPLOYEES
  webdev1:
    build: ./webdev
    container_name: webdev1
    cap_add:
      - NET_ADMIN
    networks:
      internal_B:
        ipv4_address: 10.0.2.27
  webdev2:
    build: ./webdev
    container_name: webdev2
    cap_add:
      - NET_ADMIN
    networks:
      internal_B:
        ipv4_address: 10.0.2.28

volumes:
  db-data:
  pgadmin-data:
