version: "3.8"
networks:
  webapp_B:
    driver: macvlan
    driver_opts:
      parent: ens19.3
    name: webapp_B
    ipam:
      config:
        - subnet: "10.0.3.0/24"
          gateway: "10.0.3.254"
  internal_B:
    driver: macvlan
    driver_opts:
      parent: ens19.2
    name: internal_B
    ipam:
      config:
        - subnet: "10.0.2.0/24"
          gateway: "10.0.2.254"
  dmz_B:
    driver: macvlan
    driver_opts:
      parent: ens19.1
    name: dmz_B
    ipam:
      config:
        - subnet: "10.0.1.0/24"
          gateway: "10.0.1.254"

services:
  r_b:
    build: ./router
    container_name: r_b
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    networks:
      internal_B:
        ipv4_address: 10.0.2.1
      dmz_B:
        ipv4_address: 10.0.1.2
    command: ["10.0.1.254", "10.0.1.1"]
  webapp_worker1:
    build: ./webapp_worker
    container_name: webapp_worker1
    networks:
      webapp_B:
        ipv4_address: 10.0.3.2
  webapp_worker2:
    build: ./webapp_worker
    container_name: webapp_worker2
    networks:
      webapp_B:
        ipv4_address: 10.0.3.3
  webapp:
    build: ./webapp
    container_name: webapp
    networks:
      webapp_B:
        ipv4_address: 10.0.3.1
      dmz_B:
        ipv4_address: 10.0.1.5
    command: ["10.0.1.254", "10.0.1.1"]
