version: '2'
services:
  app1:
    build: ./app1
    container_name: app1
    networks:
      net:
        ipv4_address: 10.0.2.101
    ports:
    - "5001:5000"
  app2:
    build: ./app2
    container_name: app2
    networks:
      net:
        ipv4_address: 10.0.2.102
    ports:
    - "5002:5000"
  nginx:
    build: ./nginx
    container_name: server
    cap_add:
      - NET_ADMIN
    networks:
      net:
        ipv4_address: 10.0.2.100
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2
  proxy:
    build: ../proxy
    container_name: squid
    cap_add:
      - NET_ADMIN
    volumes:
      - ~/proxy/squid.conf:/etc/squid/squid.conf
  
  client-proxy-test:
    build: ../netubuntu
    container_name: client-proxy-test
    cap_add:
      - NET_ADMIN  
      
  external_host:
    build: ../netubuntu
    container_name: external_host
    cap_add:
      - NET_ADMIN

  # In order to run this, the client_net would have to be created in this docker-compose.yml. But as it's version 2, we would have to make too many changes. 
  # As a quick solution we use a sleep 5 in the entrypoint.
  dhcp:
    build: ../dhcp-server
    container_name: dhcp-server
    cap_add:
      - NET_ADMIN
    volumes:
      - ~/dhcp-server/dhcp.conf:/etc/dhcp/dhcpd.conf
networks:
 net:
    driver: macvlan
    driver_opts:
      parent: ens20
    ipam:
      config:
        - subnet: "10.0.2.0/24"
          gateway: "10.0.2.1"