version: "3.8"
services:
  netmanager1:
    build: ./netubuntu
    container_name: netmanager1
    cap_add:
      - NET_ADMIN
    entrypoint: netmanager1_entrypoint
    networks:
      internal_C:
        ipv4_address: netmanager1_internal_c
  router_c:
    build: ./netubuntu
    container_name: router_c
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    entrypoint: router_c_entrypoint
    networks:
      internal_C:
        ipv4_address: router_c_internal_c
      DMZ_C:
        ipv4_address: router_c_dmz_c
  dhcp_c:
    build: ./dhcp
    container_name: dhcp_c
    cap_add:
      - NET_ADMIN
    networks:
      internal_C:
        ipv4_address: dhcp_c_internal_c
  dns:
    build: ./dns
    container_name: dns
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/docker/compose/porto/dns/db.myorg.net:/etc/bind/db.myorg.net
      - /etc/docker/compose/porto/dns/named.conf.local:/etc/bind/named.conf.local
      - /etc/docker/compose/porto/dns/named.conf.options:/etc/bind/named.conf.options
    entrypoint: dns_entrypoint
    networks:
      DMZ_C:
        ipv4_address: dns_dmz_c

networks:
  internal_C:
    driver: macvlan
    driver_opts:
      parent: ens19
    name: internal_C
    ipam:
      config:
        - subnet: "10.1.2.0/24"
          gateway: "10.1.2.254"
  DMZ_C:
    driver: bridge
    name: DMZ_C
    ipam:
      config:
        - subnet: "10.1.1.0/24"
          gateway: "10.1.1.254"
